### ISSUE TITLE
Как мы узнаём типы?

### ISSUE THREAD

**Issue by alf239** [newtover/python_strings#2]
> Мы видим, что в переменной s1 типа str лежат какие-то байты. В общем случае мы не можем ничего сказать, что именно они обозначают. В переменной же s2 типа unicode у нас лежит какой-то текст из шести значков, причем теперь мы можем сказать, что они обозначают:

Тут для текста неплохо бы добавить

```
>>> s1 = 'жаба'
>>> s2 = u'жаба'
>>> type(s1)
<type 'str'>
>>> type(s2)
<type 'unicode'>
>>> 

```

**Comment by newtover** [comment]
Спасибо, это тоже хорошая идея. Поправил.
